services:
    baklavaborek.service.user:
        class: BaklavaBorekBundle\Service\UserService
        arguments: ['@circle.restclient', 'http://localhost:8080/user']
    baklavaborek.form.type.maildetail:
        class: BaklavaBorekBundle\Form\MailDetailType
        arguments: ['@baklavaborek.service.user']
    baklavaborek.form.type.oder:
        class: BaklavaBorekBundle\Form\OrderType
        arguments: ['@baklavaborek.service.user']
